One of my favourite hug quotes
achasveachas/hug-bot pull request #18
Opened 2022-10-10 04:56 UTC by mishmanners

Add to the status. One of my favourite hug quotes ever.

2022-10-12 01:27 UTC, achasveachas requested changes

2022-10-12 01:27 UTC, achasveachas commented on statuses.py
> +   "Hugs are a great gift 🤗 0one size fits all, and no one minds if you return it",
Looks like there's a typo (`0one size...`).

Once it's fixed I will merge it.

2022-10-20 13:59 UTC, achasveachas approved these changes
Looks great! Thanks @mishmanners 🤗 

Let me know if you have a twitter handle so I can give you a shout out.

2022-10-20 13:59 UTC, merged

2022-10-26 06:26 UTC, mishmanners commented
Hey thank you @achasveachas. I do have a Twitter handle - MishManners
[See profile](https://twitter.com/mishmanners)

2022-10-31 04:00 UTC, mishmanners commented
Did you get my message @achasveachas 😄 would love the shout out so I can retweet!

2022-10-31 20:27 UTC, achasveachas commented
Oh, my bad @mishmanners! I must have missed the notification!